name: Build
# bei jedem Change auf einem Branch -> Kompilieren + Testen + lint checking

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up GO 
        uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - run: go test
 
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: golangci/golangci-lint-action@v3

